freenas/iocage-ix-plugins

transmission.json
Fixes https://github.com/freenas/iocage-plugin-transmission/issues/2
=> Install transmission web UI by default.

INDEX
I'd like to make the description for the MineOS more relevant.
=> More accurate description for MineOS

INDEX
These plugins are broken so hide from INDEX until fixed.
=> Delist Nextcloud and Sickrage for RC1

channels-dvr.json
Required before we cherry pick to stable
=> Correct pkg name

openvpn.json
Otherwise the actual tuns can't be created.
Ticket: #56616
=> Use allow_tun for OpenVPN plugin

openvpn.json
Otherwise the actual tuns can't be created.
Ticket: #56616
=> STABLE: Use allow_tun for OpenVPN plugin

channels-dvr.json
cc @miwi-fbsd @kmoore134 b7e08112b32e7f21aa2c1773a7c2b206f45374e2
=> Fix typo in channels-dvr repository url

INDEX, gitlab-runner.json
Gitlab-runner plugin (requires manual registration)
=> adding gitlab-runner plugin

gitlab.json
=> adding gtar dependency

INDEX
These plugins arent ready yet.
=> - Disconnect ttrss and sabnbzd

INDEX
=> Disconnect ttrss and sabnbzd

bacula-server.json, bitcoin-node.json, bru-server.json, couchpotato.json, crashplan.json, deluge.json, gitlab.json, irssi.json, nextcloud.json, openvpn.json, qbittorrent.json, redmine.json, sickrage.json, tarsnap.json, transmission.json, weechat.json, xmrig.json, zoneminder.json
- Added support for plugin_schema=2
=> NAS-102660

INDEX
Also fixed some spacing of the last 2 plugin entries.
(cherry picked from commit 2c0ebcc00719c9eed6d44493a42d18490fdb4d0b)
=> NAS-102537 update plugin descrips.

INDEX
(cherry picked from commit 5210d336a86acca0c2247c08b73d7543869c15f9)
=> update plugin descriptions with feedback (11.3).

asigra.json
This commit updates asigra manifest in master branch to reflect the latest asigra manifest using postgresql 9.
=> Update asigra manifest to reflect latest asigra manifest ( testing )

asigra.json
This commit adds asigra manifest to 11.2-release branch.
=> Add asigra manifest

asigra.json, bitcoin-node.json, gitlab.json, homebridge.json, iconik.json, mineos.json, openvpn.json, qbittorrent.json, sonarr.json
This PR normalizes plugins properties to make sure we correctly reflect boolean properties.
=> Normalize Plugin Properties

INDEX, gitlab.json
- Restore gitlab to INDEX for 11.3
Signed-off-by: Martin Wilke <miwi@ixsystems.com>
=> - Point gitlab to 12.0.6 mirror

INDEX
(cherry picked from commit ad612079f16f71fc01a1abdf75234f6ed556f26f)
=> NAS-103137 update iconik description

INDEX
Reverts freenas/iocage-ix-plugins#156
=> Revert "Add GitLab back to Index"

INDEX
Automatic cherry-pick failed. Please resolve conflicts by running:
git reset --hard HEAD~1
git cherry-pick -x 5dd9bb3d1c1186b1da7dedb905f529806aae5305
=> NAS-102944 / 11.3 / Add primary pkg for asigra (by sonicaj)

asigra.json, backuppc.json, bacula-server.json, bitcoin-node.json, bru-server.json, clamav.json, couchpotato.json, deluge.json, emby.json, gitlab-runner.json, gitlab.json, iconik.json, jenkins-lts.json, jenkins.json, mineos.json, nextcloud.json, plexmediaserver-plexpass.json, plexmediaserver.json, qbittorrent.json, radarr.json, redmine.json, rslsync.json, sonarr.json, subsonic.json, syncthing.json, tarsnap.json, tautulli.json, transmission.json, zoneminder.json
(cherry picked from commit 7a9f592f26c7720ed5672c820246c1cd39e96f1b)
=> - Move all Plugins to FreeBSD 11.3

INDEX, asigra.json, backuppc.json, bacula-server.json, bru-server.json, clamav.json, couchpotato.json, deluge.json, emby.json, gitlab-runner.json, gitlab.json, iconik.json, jenkins-lts.json, jenkins.json, mineos.json, nextcloud.json, plexmediaserver-plexpass.json, plexmediaserver.json, qbittorrent.json, radarr.json, redmine.json, rslsync.json, sonarr.json, subsonic.json, syncthing.json, tarsnap.json, tautulli.json, transmission.json, zoneminder.json
It makes more sense to have category key in the INDEX as it's better performance wise for plugin.available.
=> Fix placement of category key

plexmediaserver-plexpass.json, plexmediaserver.json
- We have recived some problem report with NAT support as example streaming on tv / mobile devices
=> NAS-104020 / 11.3 / Switch plex and plexpass to dhcp

plexmediaserver-plexpass.json, plexmediaserver.json
- We have recived some problem report with NAT support as example streaming on tv / mobile devices
=> NAS-104020 / 11.3 / Switch plex and plexpass to dhcp (by miwi-fbsd)

zoneminder.json
=> NAS-104148 / 11.3 / - switch to dhcp

zoneminder.json
=> NAS-104148 / 11.3 / - switch to dhcp (by miwi-fbsd)

INDEX
This was requested for updating https://www.freenas.org/plugins/
=> NAS-104261 / 11.3 / Added urls for plugins

INDEX
(cherry picked from commit 028d9954d7a19bc9891491ac1da9d8abd3d83366)
=> NAS-104262 / 11.3 / update asigra description

INDEX
(cherry picked from commit 028d9954d7a19bc9891491ac1da9d8abd3d83366)
=> NAS-104262 / 11.3 / update asigra description (by a-stjohn)

INDEX
Automatic cherry-pick failed. Please resolve conflicts by running:
git reset --hard HEAD~1
git cherry-pick -x fb0d1053f4f4fda262f4b6c324ef0c17a8f171f9
This was requested for updating https://www.freenas.org/plugins/
=> NAS-104261 / 11.3 / Added urls for plugins (by sirdik)

mineos.json
Forward Minecraft server ports, see NAS-105383
Please port to 11.3
=> NAS-105383 / 12.0 / NAS-105383: MineOS needs more ports forwarded

INDEX
The current Nextcloud primary package, as found in the
nextcloud.json file, is nextcloud-php74.
=> INDEX: Update Nextcloud primary package name.

asigra.json
This PR cherry-picks commits from 12.2-RELEASE branch and updates master branch to use the update packagesite.
=> Update asigra plugin for master

nextcloud.json
Reverting back to 12.1 until we have updated relevant bits for nextcloud to work with 12.2.
=> Revert to using 12.1 for nextcloud temporarily

nextcloud.json
=> Use 12.2-release for nextcloud

nextcloud.json
Buddy PR of https://github.com/freenas/iocage-plugin-nextcloud/pull/43
=> Buddy PR  for Nextcloud review 

asigra.json, nextcloud.json, plexmediaserver-plexpass.json, plexmediaserver.json
Asigra/iconik release(s) would be updated once we have 13 packagesites built for them.
=> Update nextcloud/plex plugins to use 13-stable

syncthing.json
Enables local network discovery
=> Forward all ports Syncthing needs

plexmediaserver.json
bumped 12.2-RELEASE plugins to 13.1-RELEASE
=> bumped 12.2-RELEASE plugins to 13.1-RELEASE
