template/README.md
According to the  `settings.json` the command used to set values for plugin configuration is called  `serviceset`.
=> Possible typo in the service command

mineos.json
I want to switch the repo for the MineOS plugin from "latest" to "quarterly" in order to:
1.  increase stability
2. keep things consistent with standard a jail
Thanks!
=> Switch mineos to quarterly pkg

INDEX, unificontroller-lts.json
As promised since there were no problems with primary version, @miwi-fbsd.
Note that it uses the same artifact, since there are no differences in configuration.
=> Add unificontroller LTS -

asigra.json
In order to enable dhcp support we need vnet on again. Please take note this can be only merged once the asigra plugin pr have been merge (will follow up on that)
=> - Reenable vnet

asigra.json
in order to support DHCP we need vnet on again. asigra pr need to be merged first.
=> Reenable vnet

INDEX
This commit fixes a issue where we referenced a wrong pkg name for bacula-server which resulted in failure to retrieve it's version number.
=> Fix bacula-server pkg value

INDEX
This commit adds a missing pkg_name for dnsmasq plugin.
=> Add missing pkg_name for dnsmasq plugin

INDEX
This commit introduces changes to primary_pkg key of nextcloud plugin making sure we use port's origin name instead of specifying a flavour as well which will probably fail version retrieval.
=> Use port's origin name

jenkins-lts.json, plexmediaserver-plexpass.json
In 11.2 we use name key to identify a plugin, this disrupts iocage behavior if two plugin manifests contain the same value for their name key. When retrieval of a plugin json is desired, this gets greedy and matches the first plugin manifest which has the same key.
=> Correct name key in plugin manifests

INDEX, gitlab.json
Before you approve this please approve first https://github.com/freenas/iocage-plugin-gitlab/pull/8
- Restore gitlab back to the index with the new location
Signed-off-by: Martin Wilke <miwi@ixsystems.com>
=> - Revert gitlab to 12.0.6

INDEX
We have a growing number of Channels DVR subscribers who are using FreeNAS as their server of choice. We'd like for them to be able to easily click and install our DVR server on their systems.
=> add channels-dvr plugin to the INDEX

sickchill.json
As discussed I moved sickchill to the community hub and fixed the permission error, which also fix NAS-102671
=> Update repo location

asigra.json, backuppc.json, bacula-server.json, bitcoin-node.json, bru-server.json, clamav.json, couchpotato.json, deluge.json, emby.json, gitlab-runner.json, gitlab.json, iconik.json, jenkins-lts.json, jenkins.json, mineos.json, nextcloud.json, plexmediaserver-plexpass.json, plexmediaserver.json, qbittorrent.json, radarr.json, redmine.json, rslsync.json, sonarr.json, subsonic.json, syncthing.json, tarsnap.json, tautulli.json, transmission.json, zoneminder.json
As FreeNAS 11.3 is around the corner move all plugins to FreeBSD 11.3 as well.
=> NAS-103416 / 11.3 / - Move all Plugins to FreeBSD 11.3 jails

asigra.json, bitcoin-node.json, bru-server.json, clamav.json, gitlab.json, iconik.json, qbittorrent.json, tarsnap.json
- Set DHCP for qbittorent (to many header redirects, http protocal issue from the software itself.)
- Set DHCP for gitlab need direct access for git protocol
- Remove vnet support its automated now
- Added nat support for the last plugins
=> NAS-103489 / 11.3 / NAT Support / Vnet cleanup

asigra.json, bitcoin-node.json, bru-server.json, clamav.json, gitlab.json, iconik.json, qbittorrent.json, tarsnap.json
- Set DHCP for qbittorent (to many header redirects, http protocal issue from the software itself.)
- Set DHCP for gitlab need direct access for git protocol
- Remove vnet support its automated now
- Added nat support for the last plugins
=> NAS-103489 / 11.3 / NAT Support / Vnet cleanup (by miwi-fbsd)

README.md
When developing local plugins the `-P` and `--name` option can not be used together as described in the README.md.
I'd like to suggest to prepend the name option with the `-n`.
```
~/workspace/iocage-plugins #iocage --version
Version 1.2
~/worspace/iocage-plugins # iocage fetch -P --name ./jenkins.json ip4_addr="re0|192.168.0.100"
/zroot/iocage/.plugins/github_com_freenas_iocage-ix-plugins_git/--name.json
was not found!
```
=> Fix 'Using Local File' example in README.md

qbittorrent.json
This will fix https://github.com/freenas/iocage-ports/issues/40
=> NAS-104264 / 11.3 / set explicit lang/python3

qbittorrent.json
This will fix https://github.com/freenas/iocage-ports/issues/40
=> NAS-104264 / 11.3 / set explicit lang/python3 (by miwi-fbsd)

INDEX
After some feedback directly from Plex, rename our PlexPass plugin to Beta to be consistent with their terms upstream
=> Rename (PlexPass) to (Beta) with updated description

plexmediaserver-plexpass.json, plexmediaserver.json
This change makes Plex Packages pull from FreeBSD's package sets
=> Move Plex Packages to using upstream FreeBSD latest

zoneminder.json
Update zoneminder to use mysql57 (new default version)
=> Update to mysql57 (default) for zoneminder

nextcloud.json
Nextcloud 18 can leverage the "imagick" PHP module to improve
photo/image performance.  Add a dependency on the php74-pecl-imagick-im7
package to make that module available to Nextcloud, accordingly.  Doing
so also addresses a warning displayed in the Nextcloud Web UI
Settings->Overview (i.e., /settings/admin/overview) page about the
missing "imagick" module.
=> nextcloud: Add imagick PHP module dependency.

mineos.json
Package `rdiff-backup` was renamed to `py-rdiff-backup` in the upstream "latest" repo.  This PR brings things back in sync.  
I opened NAS-106245 to track this issue.  Please port to 11.3-RELEASE
=> NAS-106245 / 12.0 / Renamed rdiff-backup to py-rdiff-backup

mineos.json
Package `rdiff-backup` was renamed to `py-rdiff-backup` in the upstream "latest" repo.  This PR brings things back in sync.  
I opened NAS-106245 to track this issue.  Please port to 11.3-RELEASE
=> NAS-106245 / 11.3 / Renamed rdiff-backup to py-rdiff-backup (by jsegaert)

backuppc.json, bitcoin-node.json, bru-server.json, clamav.json, couchpotato.json, emby.json, jenkins-lts.json, jenkins.json, mineos.json, nextcloud.json, plexmediaserver-plexpass.json, plexmediaserver.json, qbittorrent.json, radarr.json, sonarr.json, syncthing.json, tarsnap.json, tautulli.json, transmission.json, zoneminder.json
later
This gets the master / 12.0-RELEASE branches in sync, so that plugins start using FreeBSD 12.1-RELEASE as the base jail for upcoming 12.0-BETA1 and beyond.
=> Update to using 12.1-RELEASE as the base for new plugins on 12.0 and

bru-server.json
Trusted CA certs are not shipped in base OS and have to be pulled in separately by ca_root_nss package. If we don't do that, openssl rejects certs the plugin tries to use.
=> NAS-106468 / 12.1 / Add ca_root_nss package to bru-server plugin

nextcloud.json
Nextcloud 19 warns about two new missing recommended PHP modules,
bcmath and gmp, that could improve performance and compatibility.  Add
dependencies on the php74-bcmath and php74-gmp packages, accordingly.
=> nextcloud: Add bcmath and gmp PHP module deps

tautulli.json
In this [commit](https://github.com/Tautulli/Tautulli/commit/141d043a6a4651054a1b24f07a9313407a14593c), an update break tautulli plugin.
Tautulli init script use "env python" but this doesn't work with lang/python27 package.
=> Move from python2 to python3

qbittorrent.json
qbittorrent-nox is not present in 11 latest freebsd packages and is available in quarterly packages. So this PR aims to use quarterly for qbittorrent.
=> NAS-106965 / None / Use quarterly packagesite for qbittorrent

mineos.json
The MineOS plugin doesn't install anymore on FreeNAS 11.3.  This PR fixes this. Reference JIRA bug NAS-107920
I'll test the same for the ix-plugin-hub community repo, but I'd like to keep the plugin working in 11.3-RELEASE for a bit longer.
Thank you!
=> NAS-107920 / None / Move to latest version of Node.js

nextcloud.json
When running the OCC utility NextCloud complains that it's missing the PCNTL extension.
=> Add the PCNTL package for PHP as NextCloud requires this

nextcloud.json
ffmpeg is required to generate thumbnails for all types of videos
=> nextcloud: add ffmpeg to pkgs

icons/dnsmasq.svg
Note that this PR only adds the SVG file (so far), and doesn't remove the existing PNG.
That's because I've not (yet) located where the logo file is specified (and would need adjusting). :wink:
* It doesn't appear to be in this repo
* It doesn't appear to be in @timsavage's [dnsmasq plugin repo](https://github.com/timsavage/iocage-plugin-dnsmasq)
Anyone able to shed light?
=> Add Dnsmasq SVG logo

mineos.json
The MineOS plugin installation currently fails due to an issue with the git-lite package.
The reason is that the git-lite package was converted from a "slave" port to a "flavor" of the `git` port.  As a result `pkg install devel/git-lite` no longer works for some reason, but `pkg install git-lite` without the category works fine.
More information in NAS-107986
=> NAS-107986 / None / Remove pkg categories as it causes issues for git-lite

asigra.json, iconik.json
Until we have packages built for asigra/iconik for 12.2, we should continue using 11.3 release
=> Continue using 11.3 for asigra/iconik temporarily

asigra.json
This commit updates asigra version to 14.2.0.4. We are using 12.3-RELEASE temporarily until we have 13.1 available and around that time we can make the switch to 13.1 for stable/13.
=> Update asigra version for 13

syncthing.json
Syncthing is not available anymore in `latest` and `quarterly` packagesites as it is not building right now due to build failures.
Until the latest port is working, we temporarily shift to last quarter's packagesite so that syncthing plugin remains functional.
=> NAS-115717 / None / Use release_3 packagesite for syncthing

nextcloud.json
This package is needed to run /usr/local/www/nextcloud/updater/updater.phar.
Without this, the command does run, returns 0 and does absolutely nothing, which is very confusing
=> add php80-phar

nextcloud.json
Python 3.8 is not available anymore in the nextcloud plugin we install and hence python 3.8 packages fail to install
Install Python 3.9 based packages in the nextcloud plugin
=> NAS-117075 / 22.12 / Fix nextcloud installation

syncthing.json
Update Syncthing to 13.1, wanted to go with release_1 repo but the package is not in there so quarterly should suffice.
=> Update Syncthing to 13.1-RELEASE

nextcloud.json
This commit fixes an issue where 13.0 release is not working with nextcloud anymore.
```
Running post_install.sh
ld-elf.so.1: /lib/libc.so.7: version FBSD_1.7 required by /usr/local/lib/libpython3.9.so.1.0 not found
```
=> NAS-118124 / None / Use 13.1-RELEASE for nextcloud

asigra.json
12.3-RELEASE is EOL and until 13.1-RELEASE has been made publicly available, idea is to bump to 12.4 till then so that new installations can work.
=> NAS-121810 / None / Bump asigra release to 12.4
